name: Continuous Integration

on:
  push:
    branches: [ main , docker-test]

jobs:
  build-with-gradle:
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout Base Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.push.base_ref }}

      - name: Install NPM
        run: npm install

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: masiljangajji
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: masiljangajji/front-app:latest



