name: Continuous Integration

on:
  push:
    branches: [main]

env:
  PROJECT_NAME: front
  CODE_DEPLOY_APP_NAME: front-app
  DEPLOYMENT_GROUP_NAME: front-deploy

jobs:
  build-with-gradle:
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout Base Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.push.base_ref }}

      - name: Install NPM
        run: npm install

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Make zip
        run: zip -r $GITHUB_SHA.zip . -x '*.git*' -x 'node_modules/*'

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: S3 Upload zip
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://${{ secrets.BUCKET_NAME }}/${{ env.PROJECT_NAME }}/$GITHUB_SHA.zip

      - name: CodeDeploy
        run: aws deploy create-deployment --application-name $CODE_DEPLOY_APP_NAME --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name $DEPLOYMENT_GROUP_NAME --s3-location bucket=${{ secrets.BUCKET_NAME }},bundleType=zip,key=${{ env.PROJECT_NAME }}/$GITHUB_SHA.zip
